# Load CSV File

In [1]:
import csv
import pandas as pd

In [2]:
filename = '2023_Ball_by_Ball_final.csv'

with open(filename, 'r') as file:
    reader = csv.reader(file)
    # Perform data cleaning operations

In [3]:
df = pd.read_csv(filename)

In [4]:
df.head(2)

,BallID,BallUniqueID,ActualBallNo,MatchID,InningsNo,BattingTeamID,TeamName,StrikerID,NonStrikerID,BatsManName,...,HatCheck,Flag,FlagSet,PenaltyRuns,IsFifty,IsHundred,IsTwoHundred,IsHattrick,STclientID,NSTclientID
0,6AAEFE9A-3B56-4CF5-B830-F9F79361FBD0,327433.0,1.0,1046,1,35.0,Gujarat Titans,2019-100mb00000000225-a11ad1bc44c011,2019-100mb00000000062-8fa4884a17f311,Wriddhiman Saha,...,2019-100mb00000000091-8640595343ec11 - 0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1,3EC2BA93-765A-465B-BB97-49C45F96B4E4,327434.0,2.0,1046,1,35.0,Gujarat Titans,2019-100mb00000000225-a11ad1bc44c011,2019-100mb00000000062-8fa4884a17f311,Wriddhiman Saha,...,2019-100mb00000000091-8640595343ec11 - 0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN

In [5]:
df.shape

(18399, 75)

In [6]:
df.isnull().sum()

BallID            536
BallUniqueID      536
ActualBallNo      536
MatchID             0
InningsNo           0
                ...
IsHundred         536
IsTwoHundred      536
IsHattrick        536
STclientID      17647
NSTclientID     17627
Length: 75, dtype: int64

In [7]:
column_to_check = 'BallUniqueID'

In [8]:
df = df[df[column_to_check].notna()]

In [9]:
df.shape

(17863, 75)

In [10]:
df.isnull().sum()

BallID              0
BallUniqueID        0
ActualBallNo        0
MatchID             0
InningsNo           0
                ...
IsHundred           0
IsTwoHundred        0
IsHattrick          0
STclientID      17111
NSTclientID     17091
Length: 75, dtype: int64

In [11]:
columns_to_remove = ['BallID', 'STclientID', 'NSTclientID', 'IsTwoHundred', 'PenaltyRuns', 'FlagSet', 'Flag',
                     'HatCheck', 'FiveHaul', 'TotalWickets', 'BCCheck', 'IsFreeHit', 'ShotTypeID', 'BowlTypeID',
                     'OverImage', 'RunRuns', 'Ypitch', 'Xpitch', 'SNO', 'OutBatsManID', 'SESSION_NO', 'Day',
                     'UPDCommentry', 'Commentry', 'NewCommentry', 'CommentOver', 'VideoFile', 'Wickets',
                     'RunsText', 'BallRuns', 'OverName', 'StrikerID', 'NonStrikerID', 'BowlerID']

In [12]:
df = df.drop(columns=columns_to_remove)

In [13]:
df

,BallUniqueID,ActualBallNo,MatchID,InningsNo,BattingTeamID,TeamName,BatsManName,BowlerName,BowlerType,OverNo,...,BowlTypeName,ShotType,IsBouncer,BallCount,TotalRuns,BOWLING_LINE_ID,BOWLING_LENGTH_ID,IsFifty,IsHundred,IsHattrick
0,327433.0,1.0,1046,1,35.0,Gujarat Titans,Wriddhiman Saha,Deepak Chahar,NaN,1,...,OUTSWINGER,FORWARD DEFENCE,0.0,1.0,0.0,Off stump,Good Length,0.0,0.0,0.0
1,327434.0,2.0,1046,1,35.0,Gujarat Titans,Wriddhiman Saha,Deepak Chahar,NaN,1,...,OUTSWINGER,CUT SHOT,0.0,2.0,0.0,Outside Off stump,Good Length,0.0,0.0,0.0
2,327435.0,3.0,1046,1,35.0,Gujarat Titans,Wriddhiman Saha,Deepak Chahar,NaN,1,...,ANGLED IN,BACKFOOT DEFENCE,0.0,3.0,1.0,Outside Off stump,Short of Good Length,0.0,0.0,0.0
3,327436.0,4.0,1046,1,35.0,Gujarat Titans,Shubman Gill,Deepak Chahar,NaN,1,...,OUTSWINGER,BACKFOOT PUSH,0.0,4.0,2.0,Off stump,Good Length,0.0,0.0,0.0
4,327437.0,5.0,1046,1,35.0,Gujarat Titans,Wriddhiman Saha,Deepak Chahar,NaN,1,...,INSWINGER,FORWARD PUSH,0.0,5.0,3.0,Outside Off stump,Good Length,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18394,298941.0,5.0,856,2,35.0,Gujarat Titans,Rashid Khan,Deepak Chahar,NaN,19,...,STRAIGHT BALL,CUT SHOT,0.0,5.0,171.0,Outside Off stump,Short of Good Length,0.0,0.0,0.0
18395,298942.0,6.0,856,2,35.0,Gujarat Titans,Rashid Khan,Deepak Chahar,NaN,19,...,SLOW BOUNCER,STEP DOWN PULL SHOT,0.0,6.0,171.0,Outside Off stump,Short Length,0.0,0.0,0.0
18396,298943.0,1.0,856,2,35.0,Gujarat Titans,Rahul Tewatia,Tushar Deshpande,NaN,20,...,ANGLED ACROSS,LOFTED OFF DRIVE,0.0,1.0,172.0,Wide outside Off stump,Full Length,0.0,0.0,0.0
18397,298944.0,2.0,856,2,35.0,Gujarat Titans,Rahul Tewatia,Tushar Deshpande,NaN,20,...,ANGLED ACROSS,LOFTED OFF DRIVE,0.0,2.0,178.0,Outside Off stump,Full Length,0.0,0.0,0.0
18398,298945.0,3.0,856,2,35.0,Gujarat Titans,Rahul Tewatia,Tushar Deshpande,NaN,20,...,ANGLED ACROSS,FRONTFOOT STRAIGHT DRIVE,0.0,3.0,182.0,Outside Off stump,Full Length,0.0,0.0,0.0

In [14]:
df.dtypes

BallUniqueID         float64
ActualBallNo         float64
MatchID                int64
InningsNo              int64
BattingTeamID        float64
TeamName              object
BatsManName           object
BowlerName            object
BowlerType           float64
OverNo                 int64
BallNo                 int64
Runs                  object
ActualRuns           float64
IsOne                float64
IsTwo                float64
IsThree              float64
IsDotball            float64
Extras               float64
IsWide               float64
IsNoBall             float64
IsBye                float64
IsLegBye             float64
IsFour               float64
IsSix                float64
IsWicket             float64
WicketType            object
IsBowlerWicket       float64
BallName             float64
CommentStrikers       object
IsExtra              float64
IsMaiden             float64
BowlTypeName          object
ShotType              object
IsBouncer            float64
BallCount            float64
TotalRuns            float64
BOWLING_LINE_ID       object
BOWLING_LENGTH_ID     object
IsFifty              float64
IsHundred            float64
IsHattrick           float64
dtype: object

In [15]:
df['BallUniqueID'] = df['BallUniqueID'].astype(int)
df['ActualBallNo'] = df['ActualBallNo'].astype(int)
df['MatchID'] = df['MatchID'].astype(int)
df['InningsNo'] = df['InningsNo'].astype(int)
df['BattingTeamID'] = df['BattingTeamID'].astype(int)
df['OverNo'] = df['OverNo'].astype(int)
df['BallNo'] = df['BallNo'].astype(int)
df['ActualRuns'] = df['ActualRuns'].astype(int)
df['IsOne'] = df['IsOne'].astype(int)
df['IsTwo'] = df['IsTwo'].astype(int)
df['IsThree'] = df['IsThree'].astype(int)
df['IsDotball'] = df['IsDotball'].astype(int)
df['Extras'] = df['Extras'].astype(int)
df['IsWide'] = df['IsWide'].astype(int)
df['IsNoBall'] = df['IsNoBall'].astype(int)
df['IsBye'] = df['IsBye'].astype(int)
df['IsLegBye'] = df['IsLegBye'].astype(int)
df['IsFour'] = df['IsFour'].astype(int)
df['IsSix'] = df['IsSix'].astype(int)
df['IsWicket'] = df['IsWicket'].astype(int)
df['IsBowlerWicket'] = df['IsBowlerWicket'].astype(int)
df['IsExtra'] = df['IsExtra'].astype(int)
df['IsMaiden'] = df['IsMaiden'].astype(int)
df['IsBouncer'] = df['IsBouncer'].astype(int)
df['BallCount'] = df['BallCount'].astype(int)
df['TotalRuns'] = df['TotalRuns'].astype(int)
df['IsFifty'] = df['IsFifty'].astype(int)
df['IsHundred'] = df['IsHundred'].astype(int)
df['IsHattrick'] = df['IsHattrick'].astype(int)

In [16]:
df.dtypes

BallUniqueID           int32
ActualBallNo           int32
MatchID                int32
InningsNo              int32
BattingTeamID          int32
TeamName              object
BatsManName           object
BowlerName            object
BowlerType           float64
OverNo                 int32
BallNo                 int32
Runs                  object
ActualRuns             int32
IsOne                  int32
IsTwo                  int32
IsThree                int32
IsDotball              int32
Extras                 int32
IsWide                 int32
IsNoBall               int32
IsBye                  int32
IsLegBye               int32
IsFour                 int32
IsSix                  int32
IsWicket               int32
WicketType            object
IsBowlerWicket         int32
BallName             float64
CommentStrikers       object
IsExtra                int32
IsMaiden               int32
BowlTypeName          object
ShotType              object
IsBouncer              int32
BallCount              int32
TotalRuns              int32
BOWLING_LINE_ID       object
BOWLING_LENGTH_ID     object
IsFifty                int32
IsHundred              int32
IsHattrick             int32
dtype: object

In [17]:
df.columns

Index(['BallUniqueID', 'ActualBallNo', 'MatchID', 'InningsNo', 'BattingTeamID',
       'TeamName', 'BatsManName', 'BowlerName', 'BowlerType', 'OverNo',
       'BallNo', 'Runs', 'ActualRuns', 'IsOne', 'IsTwo', 'IsThree',
       'IsDotball', 'Extras', 'IsWide', 'IsNoBall', 'IsBye', 'IsLegBye',
       'IsFour', 'IsSix', 'IsWicket', 'WicketType', 'IsBowlerWicket',
       'BallName', 'CommentStrikers', 'IsExtra', 'IsMaiden', 'BowlTypeName',
       'ShotType', 'IsBouncer', 'BallCount', 'TotalRuns', 'BOWLING_LINE_ID',
       'BOWLING_LENGTH_ID', 'IsFifty', 'IsHundred', 'IsHattrick'],
      dtype='object')

In [18]:
output_filename = '2023_Ball_by_Ball_final_clean.csv'
df.to_csv(output_filename, index=False)
print ('Csv file exported')

Csv file exported